Add branch header
danielsafari143/portfolio pull request #2
Opened 2022-10-26 13:51 UTC by danielsafari143

Add inedx.css

Add style.css

2022-10-27 08:49 UTC, danielsafari143 commented
In this pull I was able to :
    - set up the linters 
    - create index.html and style.css
    -  use flexbox 
    - integrate images in my header
    - use the CSS position property

2022-10-27 09:49 UTC, Alfredbis29 requested changes
Hi @danielsafari143,

Good job so far :+1: !

There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights

- [ ] Good descriptive PR :heavy_check_mark: 
- [ ] Good commit messages :heavy_check_mark: 
- [ ] Linters are correctly settlled :heavy_check_mark: 

## Required Changes :recycle:

- [ ] Kindly check the comments under the review for more details :point_down: :point_down: 

- [ OPTIONAL]:

 - [ ] Check below the review 

**Cheers and Happy coding! :clap::clap::clap:**

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-10-27 09:49 UTC, Alfredbis29 commented on index.html
> +            <h1>My Logo</h1>
- [ ] Great job so far, As required for this project The logo (if the design has one) is on the left and has a link `a` tag not a `div` tag , kindly fix this for semantics, and user experience(UX) reason :wink:

2022-10-27 09:49 UTC, Alfredbis29 commented on index.html
> +            <img class="header-img" src="https://cdn-icons-png.flaticon.com/512/5107/5107718.png"/>
- [ ] As required for this milestone of your the hamburger button should be on right and has a `nav` tag, kindly fix this the `nav` tag is for semantic reason :upside_down_face:  :smile:

2022-10-27 09:49 UTC, Alfredbis29 commented on css/style.css
> +
- [ ] I can see that you forget to put `background-image` for this milestone as required The section has the proper background image (if the design has one). kindly fix this for aesthetic reasons :smile: 
Your Design :point_down: 
![nobackgroud](https://user-images.githubusercontent.com/88894525/198246741-6ce6ab73-b954-425e-bb17-d4a9f5703534.png)

Figma Design :point_down: 

![figma](https://user-images.githubusercontent.com/88894525/198248382-ac2e488b-5165-4e47-bb09-69051271239c.png)

2022-10-27 09:49 UTC, Alfredbis29 commented on css/style.css
> +}
- [ OPTIONAL] Please try to customize your `paragraph` and `h2` with the 'font-weight' provided by the Figma design so that it will look fantastic. :wink:

2022-10-27 09:49 UTC, Alfredbis29 commented on index.html
> +                <h2>I'm safari glad to you!</h2>
- [ ] The main title is a `h1` tag not `h2` so that google and other search engines will  know about a specific topic, in this case, you, use an `h1` tag, kindly fix this :wink: :smile:

2022-10-27 09:49 UTC, Alfredbis29 commented on index.html
> +                            </ul>
- [ ] Great work as you used `ul` `li` `a` tags to display the list of icons :clap: :smile:

2022-10-27 14:05 UTC, danielsafari143 commented
In this pull I was able to :
  - set up the linters
  - create index.html and style.css
  - use flexbox
  - integrate images in my header
  - use the CSS position property
  - correct previous errors

2022-10-27 14:10 UTC, danielsafari143 commented
In this pull I was able to :
- set up the linters
- create index.html and style.css
- use flexbox
- integrate images in my header
- use the CSS position property

2022-10-27 14:14 UTC, danielsafari143 commented
In this pull I was able to :

set up the linters
create index.html and style.css
use flexbox
integrate images in my header
use the CSS position property
correct previous errors

2022-10-27 14:50 UTC, christianbiring1 reviewed
Hi @danielsafari143 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

# STATUS: REQUEST CHANGES :recycle: 
![soclose](https://user-images.githubusercontent.com/97100091/198321792-b36f7f17-351e-4470-8827-0bc5aeaed4ec.gif)

 ## Highlights
- [ ] The PR has a descriptive `summary`

 ## Required Changes ♻️

- [ ] `I HIGHLY RECOMMEND YOU IMPLEMENT THEM FOR THEY WILL TAKE TAKE YOUR PROJECT TO THE NEXT LEVEL` :rocket: 
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 14:50 UTC, christianbiring1 commented on README.md
[OPTIONAL]
- [ ] Kindly make sure you have the `get started` telling what somebody else would do to run the copy of your repos locally :smile:

2022-10-27 14:50 UTC, christianbiring1 commented on css/style.css
> +}
[OPTIONAL]
- [ ] Kindly make sure your page is not overlapping as it is. It is supposed to fit the width of the screen and not more.
`Hint: The width can be reduced here or set with a relative value (% or vw)` :smile:

- [ ] Also make sure the typo: font family, size, weight, color, and spacing(margin, padding) are similar to the design in Figma.
your design :point_down: 

![image](https://user-images.githubusercontent.com/97100091/198316138-b956efcf-4ae5-4e6d-8f11-785323b3b953.png)
![image](https://user-images.githubusercontent.com/97100091/198316456-77fa3f6b-cf64-4506-a42d-23a2f2f1b5d5.png)

2022-10-27 14:50 UTC, christianbiring1 commented on css/style.css
> +}
Figma template :point_down: 
![image](https://user-images.githubusercontent.com/97100091/198318212-b77ee7f0-ac44-4c17-b329-cf60037161bb.png)

2022-10-27 14:50 UTC, christianbiring1 commented on index.html
> +                        </div>
[OPTIONAL]
- [ ] Kindly remove these items inside the `nav tag`, They are generic list items and not navigation links. 
You can check [here](https://www.w3schools.com/tags/tag_nav.asp#:~:text=Definition%20and%20Usage) when to use the `nav tag`
- [ ] Also the `LET'S CONNECT` is supposed to be grabbed inside a header tag `h2..6` for semantic reasons. it's not a link. kIndly change that.

2022-10-28 03:36 UTC, danielsafari143 commented
In this pull I was able to :
- set up the linters
- create index.html and style.css
- use flexbox
- integrate images in my header
- use the CSS position property

2022-10-28 04:12 UTC, topeogunleye approved these changes
### Hi @danielsafari143, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and description :heavy_check_mark:
 
## [Optional] suggestions:
* Nothing to mention.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 04:12 UTC, topeogunleye commented on css/style.css
> +  font-family: 'Poppins', Helvetica, Arial, Verdana, Tahoma, sans-serif;
[OPTIONAL]
- [ ] In order not to repeat yourself. I kindly suggest you apply your font of 'Poppins' once only to the body because 'Poppins' is the only font used for this template design.
- [ ] Kindly make sure to import Poppins from Google fonts to be able to use it.

2022-10-28 04:12 UTC, topeogunleye commented on README.md
- [OPTIONAL]

- [ ] I kindly suggest that you add a getting started to show how your project is run locally

## EXAMPLE

```
## Getting Started
To get a local copy up and running, follow the steps in Setup below.

### Prerequisites
Basic knowledge of HTML, CSS, and JavaScript.

### Setup
If you installed git you can clone the code to your machine, or download a ZIP of all the files directly.

[Download the ZIP from this location](https://github.com/danielsafari143/portfolio/archive/refs/heads/master.zip), or run the following [git](https://git-scm.com/downloads) command to clone the files to your machine:
```

```bash
git clone https://github.com/danielsafari143/portfolio.git
```

```
- Once the files are on your machine, open the _portfolio_ folder in [Visual Studio Code](https://code.visualstudio.com/)

- With the files open in Visual Studio Code, press the **Go Live** button at the bottom of the window to launch the files with [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer).

### Install

The following tools help make easier to work with sample code.

- [git](https://git-scm.com/downloads): A tool for managing source code
- [Visual Studio Code](https://code.visualstudio.com/): A source code editor
- [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer): A simple web server utility for Visual Studio Code
```

2022-10-28 04:21 UTC, merged